name: Build AppImage

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip python3-setuptools
        sudo apt-get install -y libgl1-mesa-dev
        sudo apt-get install -y appimage-builder
        
    - name: Build AppImage
      run: |
        appimage-builder --recipe AppImageBuilder.yml
        
    - name: Upload AppImage
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./ShadowMask-*-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
