# .github/workflows/release-linux.yml
name: Release Linux AppImage

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-pyqt5 python3-opencv python3-pyqt5.qtquick python3-pyqt5.qtmultimedia libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender1 libxtst6 libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0

      - name: Install AppImageBuilder
        run: |
          pip3 install --upgrade appimage-builder

      - name: Build and test Python package
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          pytest

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: ./AppImageBuilder.yml

      - name: Find AppImage
        id: find_appimage
        run: |
          echo "appimage_path=$(find . -name '*.AppImage' | head -n 1)" >> $GITHUB_OUTPUT

      - name: Upload AppImage to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_appimage.outputs.appimage_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
