name: Upload Python Package to PyPI

on:
  release:
    types: [published, prereleased]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install build and test dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install build pytest ruff

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .

      - name: Run tests
        run: |
          pytest

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write  # Required for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/shadowmask

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
