# .github/workflows/release-linux.yml
name: Release Linux AppImage

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install AppImage tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2

    - name: Build AppImage
      uses: AppImageCrafters/build-appimage-action@master
      with:
        recipe: AppImageBuilder.yml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: shadowmask-${{ github.ref_name }}.AppImage
        path: *.AppImage
